# Generated by Django 4.1.6 on 2023-04-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baptism',
            name='type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='type',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.RemoveField(
            model_name='funddetails',
            name='type',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='prayerdetails',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sermons',
            name='type',
        ),
    ]
